// Plain-language summaries; authoritative IDs and states remain in v1.9.2.
export const decisions=[
['DEC-001','Culminar con un producto mínimo viable y piloto. Aprobada.'],
['DEC-002','RFID pasivo como tecnología. Reemplazada por DEC-007.'],
['DEC-003','Usar estadística como soporte del diagnóstico. Aprobada.'],
['DEC-004','Limitar el piloto a un punto. Reemplazada por DEC-008.'],
['DEC-005','Integrar con AM solo con autorización. Aprobada.'],
['DEC-006','Conservar la propuesta aprobada como línea base externa. Aprobada.'],
['DEC-007','Ratificar RFID UHF pasivo como tecnología principal. Aprobada.'],
['DEC-008','Ratificar un único punto de control para el piloto. Aprobada.'],
['DEC-009','Desarrollar primero con códigos EPC simulados e interfaz común. Aprobada.'],
['DEC-010','Mantener presupuesto de COP 43.724.342. Aprobada.'],
['DEC-011','Incluir sustituciones temporales como función indispensable. Aprobada.'],
['DEC-012','Condicionar validación física; no extrapolar simulación. Aprobada.'],
['DEC-013','Entrar a Diseño al cerrar requisitos; hardware en paralelo. Aprobada.'],
['DEC-014','Separar lectura, evento, verificación, sustitución y contingencia. Aprobada.'],
['DEC-015','Adoptar modelo mínimo y preservar historial equipo–etiqueta. Aprobada.'],
['DEC-016','Fijar requisitos indispensables para Diseño y MVP. Aprobada.'],
['DEC-017','Adoptar la interfaz común FuenteLecturasRFID. Aprobada.'],
['DEC-018','Cerrar requisitos suficientes (P0) y entrar a Diseño. Aprobada.'],
['DEC-019','Excluir RC522 como lector UHF o evidencia física del proyecto. Aprobada.'],
['DEC-020','Tratar informe P1 y checklist como soportes subordinados. Aprobada.'],
['DEC-021','Cerrar hardware (P1) solo con EPC UHF físico reproducible y autorizado. Aprobada.'],
['DEC-022','Usar Java 21, Maven, JDBC, SQLite, Flyway y JUnit 5. Aprobada.'],
['DEC-023','Aceptar evidencia tardía AM/remodelación para el punto (P2), sin reabrir P0. Aprobada.']
];
export const requirements=[
['AC-001 · Académico','Propuesta oficial aprobada. Indispensable · Cerrado.'],
['AC-002 · Académico','Cronograma de 24 semanas. Indispensable · Cerrado.'],
['AC-003 · Académico','Presupuesto global vigente. Indispensable · Cerrado.'],
['AC-004 · Académico','Desarrollar producto mínimo viable funcional. Indispensable · Aprobado.'],
['AC-005 · Académico','Ejecutar piloto delimitado cuando existan condiciones. Indispensable · Aprobado.'],
['RF-001 · Funcional','Asociar equipo/código institucional y etiqueta. Indispensable · Implementado.'],
['RF-002 · Funcional','Capturar y guardar lecturas; admitir simulación. Indispensable · En desarrollo.'],
['RF-003 · Funcional','Registrar fecha, punto, usuario/contexto y evento. Indispensable · Aprobado.'],
['RF-004 · Funcional','Consultar última lectura e historial por equipo. Indispensable · Aprobado.'],
['RF-005 · Funcional','Comparar equipos esperados y detectados. Deseable · Aprobado.'],
['RF-006 · Funcional','Registrar contingencias manuales. Deseable · Aprobado.'],
['RF-007 · Funcional','Registrar y cerrar sustituciones temporales. Indispensable · Aprobado.'],
['TEC-001 · Técnico','Confirmar lector, configuración y disponibilidad real. Indispensable · En desarrollo.'],
['TEC-002 · Técnico','Compartir interfaz entre simulador y lector real. Indispensable · En desarrollo.'],
['DAT-001 · Datos','Separar lecturas crudas y eventos operativos. Indispensable · En desarrollo.'],
['DAT-002 · Datos','Identificar origen simulado o físico de los datos. Indispensable · En desarrollo.'],
['DAT-003 · Datos','Completar modelo mínimo de entidades del MVP. Indispensable · En desarrollo.'],
['VAL-001 · Validación','Medir lecturas correctas, omitidas y externas con hardware. Indispensable · Aprobado.'],
['VAL-002 · Validación','Medir tiempo de verificación/lectura. Deseable · Aprobado.'],
['VAL-003 · Validación','Cero eventos duplicados almacenados. Indispensable · Aprobado.'],
['VAL-004 · Validación','Definir metas tras prepruebas y antes del piloto. Indispensable · Aprobado.'],
['VAL-005 · Validación','Al menos 10 repeticiones por escenario prioritario. Indispensable · Aprobado.'],
['VAL-006 · Validación','Piloto: al menos 2 perfiles, 20 eventos y 3 sesiones. Deseable · Aprobado.'],
['OPE-001 · Operación','No afectar la operación asistencial. Indispensable · Aprobado.'],
['OPE-002 · Operación','Confirmar punto, actores, servicios, permisos y reglas. Indispensable · Aprobado.'],
['ECO-001 · Económico','Estimar costos de implementación y escalamiento. Deseable · Aprobado.'],
['ECO-002 · Económico','Hardware condicionado; desembolso personal $0. Indispensable · Aprobado.'],
['RSK-001 · Riesgo','Documentar riesgos técnicos y operativos. Deseable · Aprobado.'],
['RSK-002 · Riesgo','No extrapolar simulación a desempeño físico RFID. Indispensable · Aprobado.']
];
